// [{
//     encoding: 'ascii',
//     page: 'http://technosilaplus.com.ua'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://a-cleaning.com.ua/'
// }, {
//     encoding: 'ascii',
//     page: 'http://www.queen-service.kiev.ua'
// }, {
//     encoding: 'ascii',
//     page: 'http://cleaningservice.kiev.ua'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://cleanup.kiev.ua'
// }, {
//     encoding: 'ascii',
//     page: 'http://www.uborka-kiev.com.ua/'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://kiev.cleaning'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://himko.com.ua/'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://www.galaclean.com.ua/'
// }, {
//     encoding: 'ascii',
//     page: 'http://mister-cleaner.com.ua'
// }, {
//     encoding: 'ascii',
//     page: 'http://www.mister-clin.com.ua'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://svit-chystoty.ua/'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://cleaningstar.com.ua'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://uborka-center.kiev.ua/'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://x-clean.com.ua/contacts/'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://uborka-posle-remonta.kiev.ua/'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://uborka-kiev.com/'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://cleaningservices.kiev.ua'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://blagodarochka.com/'
// }, {
//     encoding: 'ascii',
//     page: 'http://kk-zolushka.kiev.ua'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://bleck.kiev.ua'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://moidodyr-kiev.com'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://cleaning-services.kiev.ua/'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://uborka-premium.kiev.ua/'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://armyclean.com.ua'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://www.dankeschon.com.ua'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://allon-cleaning.kiev.ua'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://impelgriffin.com.ua/'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://novaclean.kiev.ua/about/'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://zzcleaning.com'
// }, {
//     encoding: 'windows-1251',
//     page: 'http://dobrodel.in.ua/'
// }]