'use strict';
var express = require('express');
var controller = require('./user.controller');
var config = require('../../config/environment');
var auth = require('../../auth/auth.service');
var router = express.Router();
router.get('/', auth.hasRole('admin'), controller.index);
router.get('/adminindex', auth.hasRole('admin'), controller.adminindex);
router.delete('/:id', auth.hasRole('admin'), controller.destroy);
router.get('/me', auth.isAuthenticated(), controller.me);
router.put('/:id/password', auth.isAuthenticated(), controller.changePassword);
router.put('/:id/language', auth.isAuthenticated(), controller.changeLanguage);
router.put('/:id/notifications', auth.isAuthenticated(), controller.changeNotifications);
router.put('/:id/name', auth.isAuthenticated(), controller.changeName);
router.get('/:id', auth.isAuthenticated(), controller.show);
router.post('/', controller.create);
module.exports = router;