'use strict';
var express = require('express');
var controller = require('./service.controller');
var router = express.Router();
var auth = require('../../auth/auth.service');
router.get('/', auth.hasRole('admin'), controller.index);
router.get('/maincontent', controller.showMainContent);
router.get('/:id', controller.show);
router.get('/byruname/:name', controller.showByruname);
router.get('/categories/all', controller.showCategories);
router.get('/category/:subjectid', controller.showCategoriesBySubject);
router.get('/subjects/all', controller.showSubjects);
router.get('/subjectdetail/:slug/:language', controller.showSubjectDetails);
router.get('/findbyslug/:slug', controller.showBySlug);
router.get('/subcategories/icons', controller.showServicesWithIcons);
router.get('/allservices/:language', controller.showAllServices);
router.get('/subcategory/:slug/:language', controller.showSubcategory);
router.get('/subcategories/:categoryid', controller.showSubcategories);
router.post('/search/:keyword/:language', controller.showBytext);
router.post('/', auth.hasRole('admin'), controller.create);
router.put('/:id', auth.hasRole('admin'), controller.update);
module.exports = router;