'use strict';
var express = require('express');
var controller = require('./quote.controller');
var router = express.Router();
var auth = require('../../auth/auth.service');
router.get('/', auth.hasRole('admin'), controller.index);
router.get('/otherquotes/:requestid/:providerid', controller.otherquotes);
router.get('/:id', controller.show);
// router.get('/select/:id', controller.selectquote);
// router.get('/complete/:id', controller.completequote);
router.get('/allcomments/:limit', controller.allcomments);
router.get('/findbestreviews/:serviceid', controller.findbestreviews);
router.get('/comments/:providerid', controller.showprovidercomments);
router.get('/userhasquote/:providerid/:userid', controller.showuserhasquote);
router.post('/', controller.create);
router.put('/:id', controller.update);
router.patch('/:id', controller.update);
// router.delete('/:id', controller.destroy);
module.exports = router;