'use strict';
var express = require('express');
var controller = require('./provider.controller');
var router = express.Router();
var auth = require('../../auth/auth.service');
router.get('/', auth.hasRole('admin'), controller.index);
router.get('/:id', controller.show);
router.get('/slug/:slug', controller.showbyslug);
router.get('/checklink/:incominglink/:outgoinglink', controller.checklink);
router.get('/user/:userid', controller.showbyuser);
router.get('/providersbyserviceplace/:placetype/:serviceid/:oblastslug/:rayonslug/:goradslug/:rayongoradslug', controller.showbyserviceplace);
router.get('/listservices/:placetype/:oblastslug/:rayonslug/:goradslug/:rayongoradslug', controller.listservices);
router.get('/findexistinguser/:requestid/:userid', controller.findexistinguser);
router.get('/checkservice/:searchtext/:userid/:oblastslug', controller.showcheckservice);
router.post('/', controller.create);
router.post('/bulk', controller.createBulk);
router.put('/:id', controller.update);
router.patch('/:id', controller.update);
router.delete('/:id', controller.destroy);
module.exports = router;