'use strict';
var express = require('express');
var controller = require('./request.controller');
var router = express.Router();
var auth = require('../../auth/auth.service');
router.get('/', controller.index);
router.get('/adminindex', auth.hasRole('admin'), controller.adminindex);
router.get('/user/:userid', controller.indexbyuser);
router.get('/:id', controller.show);
router.get('/code/:id/:code', controller.showbycode);
router.get('/phone/:id/:phone', controller.showbyphone);
router.get('/userproviders/:userid', controller.indexbyuserproviders);
router.get('/phoneuser/:userid/:phone', controller.showbyphoneuser);
router.get('/phoneoremail/:phone/:email', controller.showbyphoneoremail);
router.get('/checkadminrequest/:phone/:email', controller.checkadminrequest);
router.get('/userlast/:userid', controller.showbyuserlast);
router.post('/', controller.create);
router.put('/:id', controller.update);
router.patch('/:id', controller.update);
router.delete('/:id', controller.destroy);
module.exports = router;